pr:
- develop

trigger:
 branches:
   include:
     - develop
  
pool:
  vmImage: ubuntu-latest
  workspace:
    clean: all
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
      
    - task: NuGetToolInstaller@1
      inputs:
          versionSpec: 
        
    - task: Ant@1
      inputs:
        buildFile: 'build.xml'
        options: 
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
    