pr:
- develop

trigger:
 branches:
   include:
     - develop
  
pool:
  vmImage: ubuntu-latest
  workspace:
    clean: all

stages:
- stage: Test
  jobs:
  - job: CIWork
    steps:
    - script: "Do CI work"
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
      
    - task: NuGetToolInstaller@1
      inputs:
          versionSpec: 
      
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
        
    - task: Ant@1
      inputs:
        buildFile: 'build.xml'
        options: 
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
    