pr:
- develop

trigger:
 branches:
   include:
     - develop
  
pool:
  vmImage: ubuntu-latest
  workspace:
    clean: all

stages:
- stage: Test
  jobs:
  - job: TestWork
    steps:
    - script: "Do test work"


